# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly
matrix:
    allow_failures:
        - julia: nightly
notifications:
  email: false
  irc:
    channels:
      - "ircs://chat.freenode.net:6697/#freeboson"
    template:
      - "%{repository}/%{branch} #%{build_number} (%{commit}) : %{message}"
    on_success: change
    on_failure: always
git:
    depth: 99999999
after_success:
  - julia -e 'cd(Pkg.dir("XKPasswd")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  - julia -e 'cd(Pkg.dir("XKPasswd")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
